### ISSUE TITLE
Clarify data center definition

### ISSUE THREAD

**Issue by Hotdog-Willie** [WhiteHouse/datacenters#21]
On page 4, the section entitled "Classification of Physical Data Centers" contains the following text:

> "For the purposes of this memorandum, rooms with at least one server, providing services (whether in a production, test, stage, development, or any other environment), are considered data centers. However, rooms containing only routing equipment, switches, security devices (such as firewalls), or other telecommunications components shall not be considered data centers."

Are rooms/ closets containing local file and print services considered data centers?  By the definition above, it seems as if they would be, yet by themselves they do not offer any consolidation opportunity.  Agencies with geographically distributed field offices (i.e., HUD, Justice, Transportation, EEOC, FAA, Treasury, DHS, etc.) will most likely have a room in that office where wide area network terminations exist as well as local file and print services.  It is suggested that these be specifically excluded to simplify and focus each agency's list on viable opportunities for optimization.

**Comment by wjwooley** [comment]
As per FDCCI, the previous definition of a data center was, "...a data center is now defined as a closet, room, floor or building for the storage, management, and dissemination of data and information. Such a repository houses computer systems and associated components, such as database, application, and storage systems and data stores. A data center generally includes redundant or backup power supplies, redundant data communications connections, environmental controls (air conditioning, fire suppression, etc.) and special security devices housed in leased (including by cloud providers), owned, collocated, or stand-alone facilities. Under this revised definition, neither square footage nor Uptime Institute tier classifications are required to define a facility as a data center."  Given the definition of "Total gross square footage" and the new definition of a "data center", this potentially gives way to multiple "data centers" of less than 5 square feet.  Is it OMB's intention that the inventory include such "data centers" that are dedicated to another purpose and only contain a server as a bi-product of another function and does not include associated components such as listed in the previous definition?

**Comment by wjwooley** [comment]
Agencies understand single servers need to be moved to a data center.  Is there a more effective way to capture rooms with a single server or servers with no racks in order to monitor the consolidation of those servers in an appropriate data center without reporting each instance as an individual data center? (i.e. count the total number of physical servers not in a data center)
