### ISSUE TITLE
Tailor closure goal to each agency

### ISSUE THREAD

**Issue by Hotdog-Willie** [WhiteHouse/datacenters#30]
In the middle of page 8, there is a sentence stating the following:

> "Furthermore, agencies must close at least 60% of non-tiered data centers government-wide."

It is suggested that this goal be tailored to each agency depending on their size, mission profile and current progress against data center consolidation goals.

A high percentage of some agencies' non-tiered data centers are actually network closets in what are essentially field offices.  These locations house network termination points as well as local computing (i.e., file and print) and are unlikely to close or be consolidated.  At a minimum it is suggested they be excluded from the data center list and not included in the closure goal.

**Comment by MarinaNitze** [comment]
I agree with @Hotdog-Willie. An agency like VA with hundreds of hospitals and field clinics is not reasonably going to shut all of that field IT off, or it would cause net harm.
