### ISSUE TITLE
Clarification on Shared Service Providers

### ISSUE THREAD

**Issue by kepetraska** [WhiteHouse/datacenters#49]
RE:  P.3, "Data centers that OGP determines satisfactory in all of their operating standards will be designated as inter-agency shared services providers."
Questions:
1)  What is the process for designating shared co-location data centers?
2)  What are the minimum requirements for obtaining shared co-location data center designation?   (i.e. what are the tests for determining the operating standards are satisfactory?)
3)  If not yet determined, when will the answers to 1 & 2, above, be provided to agencies?

**Comment by kepetraska** [comment]
RE:  P.3, "-Maintaining an online inventory of qualified inter-agency shared services providers.  -Establishing an online decision support tool to facilitate agency review, selection, and analysis of inter-agency shared services providers."
Questions:
1)  When will OGP provide agencies with the online inventory of qualified inter-agency shared services providers?
2)  When will OGP provide the online decision support tool?

**Comment by kepetraska** [comment]
RE:  P.3, "Coordinating with OMB to define qualifying operating standards for inter-agency shared services providers, creating guidance materials for becoming such a provider, and identifying and approving candidate providers."
Question:
1)  When will OMB be providing the standards and guidance?

**Comment by kepetraska** [comment]
RE:  Footnote 31,  "Note: Agencies participating as a tenant in an inter-agency shared services provider data center are not required to report metering and PUE statistics to OMB. The provider will report this data to OMB."
Questions:
1)  Will there be a separate reporting vehicle for shared data center service providers?  Or, will customer agencies simply not respond to the power and metering fields?
2)  How/when will a customer agency know if the inter-agency co-location data center has been designated as a shared service data center?
3)  What assumptions should customer agencies make with regard to whether or not an existing inter-agency co-location data center will be designated as a shared service data center prior to the owning agency completing the process for becoming "designated"?

**Comment by MovieQuoter** [comment]
Given that there are likely opportunities for agencies to provide shared services from both internal (government-owned) and 3rd party provided (contractor-owned) facilities - can industry make the assumption that OGP's Shared Services Marketplace will contain both options?
