### ISSUE TITLE
datacenters listserve isn't set up yet

### ISSUE THREAD

**Issue by konklone** [WhiteHouse/datacenters#8]
From https://datacenters.cio.gov/community/ -

> Executive agencies are encouraged to join the Data Centers listserv by emailing listserv@listserv.gsa.gov with no subject and "subscribe datacenters" in the body (from a .gov or .mil email address only.)

But I gave this a shot with my .gov and got:

> No LISTSERV list by the name of "DATACENTERS" is known to exist.

You may want to remove this until that works, or just go and create the listserve before the policy text is widely promoted.

**Comment by gbinal** [comment]
FWIW, I'm happy to get this set up asap if helpful.  Holler if you need a hand.

**Comment by dpomeroy** [comment]
Thanks, Gray! @gbinal   =]
I think we have the listserve up and running now.

**Comment by konklone** [comment]
Yep! It works now.
