### ISSUE TITLE
Site styles are broken in Chrome and Firefox

### ISSUE THREAD

**Issue by afeld** [WhiteHouse/datacenters#87]
The underlying issue isn't totally obvious to me...

![screen shot 2016-06-30 at 1 17 56 pm](https://cloud.githubusercontent.com/assets/86842/16497463/233a87d4-3ec5-11e6-812b-eb92cbb24721.png)

Works in Safari.

/cc @konklone

**Comment by jalbertbowden** [comment]
its serving up style sheets over http, but the site is https. i bet if you change <code>{{ site.baseurl }}</code> in https://github.com/WhiteHouse/datacenters/blob/gh-pages/_layouts/default.html they will render

**Comment by mattbailey0** [comment]
Thanks both!  Fixed.
